# Generated by Django 5.2.4 on 2025-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_students',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='group',
            name='monthly_fee',
            field=models.PositiveSmallIntegerField(default=300000),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
