# Generated by Django 5.2.4 on 2025-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_group_max_students_alter_group_monthly_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='date',
        ),
        migrations.AlterField(
            model_name='homework',
            name='task',
            field=models.TextField(max_length=300),
        ),
    ]
